// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "Categories.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class Categories
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   CSharpDataModelsGenerator v17.99.00
// App/Edition: Events, Courses and Registration/staging
// User:        2sic Web-Developer
// When:        2024-06-18 09:15:56Z
namespace AppCode.Data
{
  // This is a generated class for Categories 
  // To extend/modify it, see instructions above.

  /// <summary>
  /// Categories data. <br/>
  /// Generated 2024-06-18 09:15:56Z. Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// Default properties such as `.Title` or `.Id` are provided in the base class. <br/>
  /// Most properties have a simple access, such as `.PageTitle`. <br/>
  /// For other properties or uses, use methods such as
  /// .IsNotEmpty("FieldName"), .String("FieldName"), .Children(...), .Picture(...), .Html(...).
  /// </summary>
  public partial class Categories: AutoGenerated.ZAutoGenCategories
  {  }
}

namespace AppCode.Data.AutoGenerated
{
  /// <summary>
  /// Auto-Generated base class for Default.Categories in separate namespace and special name to avoid accidental use.
  /// </summary>
  public abstract class ZAutoGenCategories: Custom.Data.CustomItem
  {
    /// <summary>
    /// PageTitle as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("PageTitle", scrubHtml: true) etc.
    /// </summary>
    public string PageTitle => _item.String("PageTitle", fallback: "");

    /// <summary>
    /// Title as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Title", scrubHtml: true) etc.
    /// </summary>
    /// <remarks>
    /// This hides base property Title.
    /// To access original, convert using AsItem(...) or cast to ITypedItem.
    /// Consider renaming this field in the underlying content-type.
    /// </remarks>
    public new string Title => _item.String("Title", fallback: "");
  }
}