// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "EventSettings.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class EventSettings
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   CSharpDataModelsGenerator v17.99.00
// App/Edition: Events, Courses and Registration/staging
// User:        2sic Web-Developer
// When:        2024-06-18 09:15:56Z
using System.Collections.Generic;

namespace AppCode.Data
{
  // This is a generated class for EventSettings 
  // To extend/modify it, see instructions above.

  /// <summary>
  /// EventSettings data. <br/>
  /// Generated 2024-06-18 09:15:56Z. Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// Default properties such as `.Title` or `.Id` are provided in the base class. <br/>
  /// Most properties have a simple access, such as `.Categories`. <br/>
  /// For other properties or uses, use methods such as
  /// .IsNotEmpty("FieldName"), .String("FieldName"), .Children(...), .Picture(...), .Html(...).
  /// </summary>
  public partial class EventSettings: AutoGenerated.ZAutoGenEventSettings
  {  }
}

namespace AppCode.Data.AutoGenerated
{
  /// <summary>
  /// Auto-Generated base class for Default.EventSettings in separate namespace and special name to avoid accidental use.
  /// </summary>
  public abstract class ZAutoGenEventSettings: Custom.Data.CustomItem
  {
    /// <summary>
    /// Categories as list of Categories.
    /// </summary>
    /// <remarks>
    /// Generated to return child-list child because field settings had Multi-Value=true. The type Categories was specified in the field settings.
    /// </remarks>
    /// <returns>
    /// An IEnumerable of specified type, but can be empty.
    /// </returns>
    public IEnumerable<Categories> Categories => _categories ??= _item.Children<Categories>("Categories");
    private IEnumerable<Categories> _categories;

    /// <summary>
    /// ItemsPerPage as int. <br/>
    /// To get other types use methods such as .Decimal("ItemsPerPage")
    /// </summary>
    public int ItemsPerPage => _item.Int("ItemsPerPage");

    /// <summary>
    /// Title as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Title", scrubHtml: true) etc.
    /// </summary>
    /// <remarks>
    /// This hides base property Title.
    /// To access original, convert using AsItem(...) or cast to ITypedItem.
    /// Consider renaming this field in the underlying content-type.
    /// </remarks>
    public new string Title => _item.String("Title", fallback: "");
  }
}